export const VAT_RATE = 0.1;

export const ORDER_STATUS_PENDING_PAYMENT = 'PENDING_PAYMENT';
export const ORDER_STATUS_PENDING_PROCESSING = 'PENDING_PROCESSING';
export const DELIVERY_METHOD_STANDARD = 'STANDARD';

export const PAYMENT_TRANSACTION_PROVIDER_PLACE_ORDER = 'PLACE_ORDER';
export const PAYMENT_STATUS_SUCCESS = 'SUCCESS';

export const UNAVAILABLE_PRODUCT_STATUSES = [
  'DEACTIVATED',
  'DELETED',
  'INACTIVE',
  'UNAVAILABLE',
];
